# Generated by Django 4.0.6 on 2022-09-02 13:47

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва новини')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис мети новини', max_length=5000, null=True, verbose_name='Короткий опис')),
                ('text', models.TextField(help_text='не більше 15 000 символів', max_length=15000, null=True, verbose_name='Текст новини')),
                ('pub_date', models.DateField(null=True, verbose_name='Дата новини')),
                ('photo_1', models.ImageField(max_length=500, null=True, upload_to=news.models.News.directory_path, verbose_name='Картинка новини')),
                ('photo_2', models.ImageField(blank=True, max_length=500, null=True, upload_to=news.models.News.directory_path, verbose_name='Картинка новини')),
                ('photo_3', models.ImageField(blank=True, max_length=500, null=True, upload_to=news.models.News.directory_path, verbose_name='Картинка новини')),
                ('photo_4', models.ImageField(blank=True, max_length=500, null=True, upload_to=news.models.News.directory_path, verbose_name='Картинка новини')),
                ('photo_5', models.ImageField(blank=True, max_length=500, null=True, upload_to=news.models.News.directory_path, verbose_name='Картинка новини')),
                ('category', models.ManyToManyField(help_text='оберіть категорію/категорії', to='nio_app.categories', verbose_name='Оберіть категорію')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=5000, verbose_name='Повідомлення')),
                ('pub_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата коментарія')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новина')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.reviewsnews', verbose_name='До кого')),
            ],
            options={
                'verbose_name': 'Відгук на новину',
                'verbose_name_plural': 'Відгуки на новину',
                'ordering': ['-pub_date'],
            },
        ),
    ]
