# Generated by Django 4.0.6 on 2022-07-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва підрозділу')),
                ('abr', models.CharField(help_text='не більше ніж 10 символів', max_length=10, verbose_name='Абрівіатура підрозділу')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис підрозділу', max_length=5000, verbose_name='Опис підрозділу')),
                ('num_staff', models.IntegerField(null=True, verbose_name='Кількість персоналу')),
                ('num_projects', models.IntegerField(null=True, verbose_name='Кількість проектів')),
                ('num_docs', models.IntegerField(null=True, verbose_name='Загальна кількість документації')),
            ],
            options={
                'verbose_name': 'Підрозділи',
                'verbose_name_plural': 'Підрозділи',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='ПІБ')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('tabel', models.CharField(help_text='не більше ніж 5 символів', max_length=5, unique=True, verbose_name='Табельный номер')),
                ('prof', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Професія')),
                ('oklad', models.IntegerField(verbose_name='Оклад')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата народження')),
                ('phone', models.CharField(help_text='формат +38(ХХХ)-ХХХ-ХХ-ХХ', max_length=18, verbose_name='Номер телефону')),
                ('adress', models.CharField(help_text='формат пр/вул/провулок ХХХХХ д.ХХ кв.ХХ', max_length=100, verbose_name='Домашня адреса')),
                ('photo', models.ImageField(upload_to='workers_foto/', verbose_name='Фото')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.divisions', verbose_name='Назва підрозділу')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва підрозділу')),
                ('abr', models.CharField(help_text='не більше ніж 10 символів', max_length=10, verbose_name='Абрівіатура підрозділу')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис підрозділу', max_length=5000, verbose_name='Опис підрозділу')),
                ('num_staff', models.IntegerField(null=True, verbose_name='Кількість персоналу')),
                ('num_projects', models.IntegerField(null=True, verbose_name='Кількість проектів')),
                ('num_docs', models.IntegerField(null=True, verbose_name='Загальна кількість документації')),
                ('boss', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='ПІБ керівника')),
                ('photo', models.ImageField(upload_to='workers_foto/', verbose_name='Фото')),
                ('divisions', models.ManyToManyField(to='nio_app.divisions', verbose_name='Підрозділи')),
            ],
            options={
                'verbose_name': 'Загальна інфо',
                'verbose_name_plural': 'Загальна інфо',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть назву документу', max_length=500, verbose_name='Назва документа')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='URL')),
                ('type', models.CharField(choices=[('М', 'Методика'), ('П', 'Паспорт'), ('КЕ', 'Керівництво з експлуатації'), ('ТД', 'Технична довідка'), ('ЗТ', 'Технічний звіт'), ('ТІ', 'Технологічна інструкция'), ('І', 'Інше'), (None, 'Тип')], help_text='Оберіть тип документу', max_length=50, verbose_name='Тип документу')),
                ('status', models.CharField(choices=[('Р', 'Розробка'), ('У', 'Узгодження'), ('В', 'Впроваджено'), (None, 'Статус')], help_text='Поточний статус документу', max_length=50, verbose_name='Статус документу')),
                ('doc', models.FileField(upload_to='archives/')),
                ('release_date', models.DateField(blank=True, help_text='Введіть дату впровадження', null=True, verbose_name='Дата впровадження')),
                ('author', models.ManyToManyField(help_text='Оберіть автора/авторів документу', related_name='authors', to='nio_app.staff', verbose_name='Автор')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='div', to='nio_app.divisions', verbose_name='Назва підрозділу')),
            ],
            options={
                'verbose_name': 'Документація',
                'verbose_name_plural': 'Документація',
                'ordering': ['div'],
            },
        ),
    ]
