# Generated by Django 4.0.6 on 2022-09-01 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import nio_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Категорія')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Вкажіть пов'язаний підрозділ", max_length=100, verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Підрозділ взаємодії',
                'verbose_name_plural': 'Підрозділи взаємодії',
                'ordering': ['name'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва підрозділу')),
                ('abr', models.CharField(help_text='не більше ніж 10 символів', max_length=10, verbose_name='Абрівіатура підрозділу')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис підрозділу', max_length=5000, verbose_name='Опис підрозділу')),
                ('num_staff', models.IntegerField(blank=True, default=0, null=True, verbose_name='Кількість персоналу')),
                ('num_projects', models.IntegerField(null=True, verbose_name='Кількість проектів')),
                ('num_docs', models.IntegerField(null=True, verbose_name='Загальна кількість документації')),
                ('boss', models.CharField(blank=True, help_text="Призвище Ім'я", max_length=50, null=True, verbose_name='ПІБ керівника')),
                ('photo', models.ImageField(upload_to='boss_foto/', verbose_name='Фото')),
                ('coops', models.ManyToManyField(to='nio_app.cooperation', verbose_name='Підрозділи взаємодії')),
            ],
            options={
                'verbose_name': 'Підрозділи',
                'verbose_name_plural': 'Підрозділи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(help_text='Вкажіть приміщення або цех(приміщення)', max_length=100, verbose_name='Приміщення')),
            ],
            options={
                'verbose_name': 'Приміщення',
                'verbose_name_plural': 'Приміщення',
                'ordering': ['loc'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва новини')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис мети новини', max_length=5000, null=True, verbose_name='Короткий опис')),
                ('text', models.TextField(help_text='не більше 15 000 символів', max_length=15000, null=True, verbose_name='Текст новини')),
                ('pub_date', models.DateField(null=True, verbose_name='Дата новини')),
                ('photo_1', models.ImageField(max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини')),
                ('photo_2', models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини')),
                ('photo_3', models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини')),
                ('photo_4', models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини')),
                ('photo_5', models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини')),
                ('category', models.ManyToManyField(help_text='оберіть категорію/категорії', to='nio_app.categories', verbose_name='Оберіть категорію')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва проекту')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис мети проекту', max_length=5000, verbose_name='Опис підрозділу')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва публікації')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис мети публікації', max_length=5000, null=True, verbose_name='Короткий опис')),
                ('text', models.TextField(help_text='не більше 50 000 символів', max_length=50000, null=True, verbose_name='Текст публікації')),
                ('pub_date', models.DateField(null=True, verbose_name='Дата піблікації')),
                ('photo_1', models.ImageField(max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('photo_2', models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('photo_3', models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('photo_4', models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('photo_5', models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('doc', models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Файл публікації')),
            ],
            options={
                'verbose_name': 'Публікація',
                'verbose_name_plural': 'Публікації',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Theses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Теза')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='theses/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Теза',
                'verbose_name_plural': 'Тези',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='ПІБ')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('tabel', models.CharField(help_text='не більше ніж 5 символів', max_length=5, unique=True, verbose_name='Табельный номер')),
                ('prof', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Посада')),
                ('oklad', models.IntegerField(verbose_name='Оклад')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата народження')),
                ('phone', models.CharField(help_text='формат +38(ХХХ)-ХХХ-ХХ-ХХ', max_length=18, verbose_name='Номер телефону')),
                ('adress', models.CharField(help_text='формат пр/вул/провулок ХХХХХ д.ХХ кв.ХХ', max_length=100, verbose_name='Домашня адреса')),
                ('photo', models.ImageField(upload_to='workers_foto/', verbose_name='Фото')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.divisions', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='ReviewsPubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=5000, verbose_name='Повідомлення')),
                ('pub_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата коментарія')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.reviewspubs', verbose_name='До кого')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nio_app.publications', verbose_name='Публікація')),
            ],
            options={
                'verbose_name': 'Відгук на публікацію',
                'verbose_name_plural': 'Відгуки на публікацію',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=5000, verbose_name='Повідомлення')),
                ('pub_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата коментарія')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nio_app.news', verbose_name='Новина')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.reviewsnews', verbose_name='До кого')),
            ],
            options={
                'verbose_name': 'Відгук на новину',
                'verbose_name_plural': 'Відгуки на новину',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AddField(
            model_name='publications',
            name='author',
            field=models.ManyToManyField(help_text='Оберіть автора/авторів публікації', to='nio_app.staff', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='publications',
            name='category',
            field=models.ManyToManyField(help_text='оберіть категорію/категорії', to='nio_app.categories', verbose_name='Оберіть категорію'),
        ),
        migrations.AddField(
            model_name='publications',
            name='div',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.divisions', verbose_name='Назва підрозділу'),
        ),
        migrations.CreateModel(
            name='ProjectsPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.ProjectsPics.directory_path, verbose_name='Картинка проекту')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Картинка проекту',
                'verbose_name_plural': 'Картинки проектів',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='ProjectsDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.ProjectsDocs.directory_path)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Документ проекту',
                'verbose_name_plural': 'Документи проектів',
                'ordering': ['project'],
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='author',
            field=models.ManyToManyField(help_text='Оберіть автора/авторів проекту', to='nio_app.staff', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(help_text='оберіть категорію/категорії', to='nio_app.categories', verbose_name='Оберіть категорію'),
        ),
        migrations.AddField(
            model_name='projects',
            name='div',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.divisions', verbose_name='Назва підрозділу'),
        ),
        migrations.AddField(
            model_name='projects',
            name='docs',
            field=models.ManyToManyField(to='nio_app.projectsdocs', verbose_name='Документ до проекту'),
        ),
        migrations.AddField(
            model_name='projects',
            name='pics',
            field=models.ManyToManyField(to='nio_app.projectspics', verbose_name='Картинка до проекту'),
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва підрозділу')),
                ('abr', models.CharField(help_text='не більше ніж 10 символів', max_length=10, verbose_name='Абрівіатура підрозділу')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис підрозділу', max_length=5000, verbose_name='Опис підрозділу')),
                ('num_staff', models.IntegerField(blank=True, null=True, verbose_name='Кількість персоналу')),
                ('num_projects', models.IntegerField(blank=True, null=True, verbose_name='Кількість проектів')),
                ('num_docs', models.IntegerField(blank=True, null=True, verbose_name='Загальна кількість документації')),
                ('boss', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='ПІБ керівника')),
                ('photo', models.ImageField(upload_to='workers_foto/', verbose_name='Фото')),
                ('divisions', models.ManyToManyField(to='nio_app.divisions', verbose_name='Підрозділи')),
            ],
            options={
                'verbose_name': 'Загальна інфо',
                'verbose_name_plural': 'Загальна інфо',
            },
        ),
        migrations.CreateModel(
            name='DivisionsPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=nio_app.models.DivisionsPics.directory_path, verbose_name='Фото підрозділу')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.divisions', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Картинка до підрозділу',
                'verbose_name_plural': 'Картинки до підрозділів',
                'ordering': ['div'],
            },
        ),
        migrations.AddField(
            model_name='divisions',
            name='locs',
            field=models.ManyToManyField(to='nio_app.location', verbose_name='Розміщення'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='pics',
            field=models.ManyToManyField(to='nio_app.divisionspics', verbose_name='Картинка до підрозділу'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='theses',
            field=models.ManyToManyField(to='nio_app.theses', verbose_name='Тези'),
        ),
    ]
