# Generated by Django 4.0.6 on 2022-09-02 13:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Категорія')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Вкажіть пов'язаний підрозділ", max_length=100, verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Підрозділ взаємодії',
                'verbose_name_plural': 'Підрозділи взаємодії',
                'ordering': ['name'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(help_text='Вкажіть приміщення або цех(приміщення)', max_length=100, verbose_name='Приміщення')),
            ],
            options={
                'verbose_name': 'Приміщення',
                'verbose_name_plural': 'Приміщення',
                'ordering': ['loc'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва підрозділу')),
                ('abr', models.CharField(help_text='не більше ніж 10 символів', max_length=10, verbose_name='Абрівіатура підрозділу')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис підрозділу', max_length=5000, verbose_name='Опис підрозділу')),
                ('num_staff', models.IntegerField(blank=True, null=True, verbose_name='Кількість персоналу')),
                ('num_projects', models.IntegerField(blank=True, null=True, verbose_name='Кількість проектів')),
                ('num_docs', models.IntegerField(blank=True, null=True, verbose_name='Загальна кількість документації')),
                ('boss', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='ПІБ керівника')),
                ('photo', models.ImageField(upload_to='workers_foto/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Загальна інфо',
                'verbose_name_plural': 'Загальна інфо',
            },
        ),
        migrations.CreateModel(
            name='Theses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Теза')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='theses/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Теза',
                'verbose_name_plural': 'Тези',
            },
        ),
    ]
