# Generated by Django 4.0.6 on 2022-08-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='docs',
            field=models.ManyToManyField(to='nio_app.projectsdocs', verbose_name='Документ до проекту'),
        ),
        migrations.AddField(
            model_name='projects',
            name='pics',
            field=models.ManyToManyField(to='nio_app.projectspics', verbose_name='Картинка до проекту'),
        ),
    ]
