# Generated by Django 4.0.4 on 2022-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='author',
            field=models.ManyToManyField(help_text='Введіть автора документу', to='nio_app.staff', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_type',
            field=models.CharField(choices=[('М', 'Методика'), ('П', 'Паспорт'), ('КЕ', 'Керівництво з експлуатації'), ('ТД', 'Технична довідка'), ('ЗТ', 'Технічний звіт'), ('ТІ', 'Технологічна інструкция'), ('І', 'Інше')], help_text='Введіть тип документу', max_length=50, verbose_name='Тип документу'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(help_text='формат +38(ХХХ)-ХХХ-ХХ-ХХ', max_length=18, verbose_name='Номер телефону'),
        ),
    ]
