# Generated by Django 4.0.6 on 2022-08-05 13:59

from django.db import migrations, models
import nio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='photo_1',
            field=models.ImageField(null=True, upload_to=nio_app.models.Divisions.directory_path, verbose_name='Фото підрозділу'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=nio_app.models.Divisions.directory_path, verbose_name='Фото підрозділу'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=nio_app.models.Divisions.directory_path, verbose_name='Фото підрозділу'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=nio_app.models.Divisions.directory_path, verbose_name='Фото підрозділу'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=nio_app.models.Divisions.directory_path, verbose_name='Фото підрозділу'),
        ),
    ]
