# Generated by Django 4.0.6 on 2022-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='boss',
            field=models.CharField(blank=True, help_text='не більше ніж 200 символів', max_length=200, null=True, verbose_name='ПІБ керівника'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='workers_foto/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='main',
            name='num_docs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Загальна кількість документації'),
        ),
        migrations.AlterField(
            model_name='main',
            name='num_projects',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість проектів'),
        ),
        migrations.AlterField(
            model_name='main',
            name='num_staff',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість персоналу'),
        ),
    ]
