# Generated by Django 4.0.4 on 2022-06-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_type',
            field=models.CharField(choices=[('М', 'Методика'), ('П', 'Паспорт'), ('РЭ', 'Руководство по эксплуатации'), ('ТС', 'Техническая справка'), ('ОТ', 'Технический отчет'), ('ТИ', 'Технологическая инструкция'), ('Д', 'Другое')], help_text='Введите тип документа', max_length=50, verbose_name='Тип документа'),
        ),
    ]
