# Generated by Django 4.0.6 on 2022-08-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0002_alter_divisions_photo_1_alter_divisions_photo_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisions',
            old_name='photo_boss',
            new_name='photo',
        ),
    ]
