# Generated by Django 4.0.6 on 2022-08-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0002_remove_documents_description_remove_documents_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='description',
            field=models.TextField(help_text='Введіть короткий опис документа (мета)', max_length=5000, null=True, verbose_name='Опис документа'),
        ),
        migrations.AddField(
            model_name='documents',
            name='number',
            field=models.CharField(help_text='Введіть номер документу', max_length=20, null=True, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='documents',
            name='year',
            field=models.CharField(help_text='Введіть рік випуску', max_length=4, null=True, verbose_name='Рік випуску'),
        ),
    ]
