# Generated by Django 4.0.4 on 2022-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0002_alter_documents_author_alter_documents_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='tabel',
            field=models.IntegerField(unique=True, verbose_name='Табельный номер'),
        ),
    ]
