# Generated by Django 4.0.6 on 2022-07-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0002_theses_alter_cooperation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='num_staff',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кількість персоналу'),
        ),
    ]
