# Generated by Django 4.0.6 on 2022-07-27 11:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0002_divisions_boss_divisions_photo_alter_main_num_docs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Вкажіть пов'язаний підрозділ", max_length=100, verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Підрозділ взаємодії',
                'verbose_name_plural': 'Підрозділи взаємодії',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(help_text='Вкажіть приміщення або цех(приміщення)', max_length=100, verbose_name='Приміщення')),
            ],
            options={
                'verbose_name': 'Приміщення',
                'verbose_name_plural': 'Приміщення',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
