# Generated by Django 4.0.6 on 2022-07-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0003_alter_divisions_num_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='photo',
            field=models.ImageField(null=True, upload_to='workers_foto/', verbose_name='Фото'),
        ),
    ]
