# Generated by Django 4.0.6 on 2022-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0003_rename_photo_boss_divisions_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='boss',
            field=models.CharField(blank=True, help_text="Призвище Ім'я", max_length=50, null=True, verbose_name='ПІБ керівника'),
        ),
    ]
