# Generated by Django 4.0.4 on 2022-06-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0003_alter_staff_tabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='division_name',
            field=models.ForeignKey(help_text='не більше ніж 50 символів', null=True, on_delete=django.db.models.deletion.CASCADE, to='nio_app.divisions', verbose_name='Назва підрозділу'),
        ),
    ]
