# Generated by Django 4.0.6 on 2022-07-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0003_cooperation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='coops',
            field=models.ManyToManyField(to='nio_app.cooperation', verbose_name='Підрозділи взаємодії'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='locs',
            field=models.ManyToManyField(to='nio_app.location', verbose_name='Розміщення'),
        ),
    ]
