# Generated by Django 4.0.6 on 2022-08-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0003_documents_description_documents_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['-release_date'], 'verbose_name': 'Документація', 'verbose_name_plural': 'Документація'},
        ),
        migrations.AddField(
            model_name='documents',
            name='slug_type',
            field=models.SlugField(max_length=500, null=True, unique=True, verbose_name='URL_Типу'),
        ),
    ]
