# Generated by Django 4.0.6 on 2022-07-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0004_alter_divisions_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='photo',
            field=models.ImageField(upload_to='workers_foto/', verbose_name='Фото'),
        ),
    ]
