# Generated by Django 4.0.6 on 2022-08-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0004_alter_documents_options_documents_slug_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='slug_type',
        ),
    ]
