# Generated by Django 4.0.6 on 2022-07-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0004_divisions_coops_divisions_locs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisions',
            options={'ordering': ['name'], 'verbose_name': 'Підрозділи', 'verbose_name_plural': 'Підрозділи'},
        ),
    ]
