# Generated by Django 4.0.6 on 2022-08-04 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0006_alter_divisions_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='div',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.divisions', verbose_name='Підрозділ'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='prof',
            field=models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Посада'),
        ),
    ]
