# Generated by Django 4.0.6 on 2022-08-04 06:26

from django.db import migrations, models
import nio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0007_alter_staff_div_alter_staff_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Теза')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.RenameField(
            model_name='divisions',
            old_name='photo',
            new_name='photo_boss',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='doc',
        ),
        migrations.AddField(
            model_name='divisions',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Фото підрозділу'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Фото підрозділу'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Фото підрозділу'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Фото підрозділу'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='photo_5',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Фото підрозділу'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(help_text='Введіть короткий опис мети публікації', max_length=5000, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_5',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='Дата піблікації'),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='Введіть короткий опис мети публікації', max_length=15000, null=True, verbose_name='Текст новини'),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_1',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_10',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_2',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_3',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_4',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_5',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_6',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_7',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_8',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='doc_9',
            field=models.FileField(null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка проекту'),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка проекту'),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка проекту'),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка проекту'),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo_5',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка проекту'),
        ),
        migrations.AddField(
            model_name='publications',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка публікації'),
        ),
        migrations.AddField(
            model_name='publications',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка публікації'),
        ),
        migrations.AddField(
            model_name='publications',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка публікації'),
        ),
        migrations.AddField(
            model_name='publications',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка публікації'),
        ),
        migrations.AddField(
            model_name='publications',
            name='photo_5',
            field=models.ImageField(null=True, upload_to='theses/', verbose_name='Картинка публікації'),
        ),
        migrations.AddField(
            model_name='publications',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='Дата піблікації'),
        ),
        migrations.AddField(
            model_name='publications',
            name='text',
            field=models.TextField(help_text='Введіть короткий опис мети публікації', max_length=25000, null=True, verbose_name='Текст публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='description',
            field=models.TextField(help_text='Введіть короткий опис мети публікації', max_length=5000, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(help_text='оберіть категорію/категорії', to='nio_app.categories', verbose_name='Оберіть категорію'),
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(help_text='оберіть категорію/категорії', to='nio_app.categories', verbose_name='Оберіть категорію'),
        ),
        migrations.AddField(
            model_name='publications',
            name='category',
            field=models.ManyToManyField(help_text='оберіть категорію/категорії', to='nio_app.categories', verbose_name='Оберіть категорію'),
        ),
    ]
