# Generated by Django 4.0.6 on 2022-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0008_categories_rename_photo_divisions_photo_boss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_5',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='publics/', verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='publics/', verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='publics/', verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='publics/', verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_5',
            field=models.ImageField(null=True, upload_to='publics/', verbose_name='Картинка публікації'),
        ),
    ]
