# Generated by Django 4.0.6 on 2022-08-04 09:55

from django.db import migrations, models
import nio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0009_alter_categories_name_alter_news_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='doc',
            field=models.FileField(null=True, upload_to=nio_app.models.Publications.directory_path),
        ),
    ]
