# Generated by Django 4.0.6 on 2022-08-04 09:57

from django.db import migrations, models
import nio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0010_alter_publications_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='doc',
            field=models.FileField(null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Файл публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='publics/', verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='publics/', verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='publics/', verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='publics/', verbose_name='Картинка публікації'),
        ),
    ]
