# Generated by Django 4.0.6 on 2022-08-04 09:59

from django.db import migrations, models
import nio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0011_alter_publications_doc_alter_publications_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='theses/', verbose_name='Фото підрозділу'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='theses/', verbose_name='Фото підрозділу'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='theses/', verbose_name='Фото підрозділу'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='theses/', verbose_name='Фото підрозділу'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_10',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_2',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_3',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_4',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_5',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_6',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_7',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_8',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_9',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='theses/', verbose_name='Картинка проекту'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='theses/', verbose_name='Картинка проекту'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='theses/', verbose_name='Картинка проекту'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='theses/', verbose_name='Картинка проекту'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Файл публікації'),
        ),
    ]
