# Generated by Django 4.0.6 on 2022-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0013_alter_projects_photo_1_alter_projects_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='text',
            field=models.TextField(help_text='Введіть короткий опис мети публікації', max_length=50000, null=True, verbose_name='Текст публікації'),
        ),
    ]
