# Generated by Django 4.0.6 on 2022-08-04 10:38

from django.db import migrations, models
import nio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0014_alter_publications_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo_1',
            field=models.ImageField(max_length=500, null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_2',
            field=models.ImageField(max_length=500, null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_3',
            field=models.ImageField(max_length=500, null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_4',
            field=models.ImageField(max_length=500, null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_5',
            field=models.ImageField(max_length=500, null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_1',
            field=models.FileField(max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_10',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_2',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_3',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_4',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_5',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_6',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_7',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_8',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc_9',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_1',
            field=models.ImageField(max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path, verbose_name='Картинка проекту'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path, verbose_name='Картинка проекту'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path, verbose_name='Картинка проекту'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path, verbose_name='Картинка проекту'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_5',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Projects.directory_path, verbose_name='Картинка проекту'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='doc',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Файл публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_1',
            field=models.ImageField(max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo_5',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.Publications.directory_path, verbose_name='Картинка публікації'),
        ),
    ]
