# Generated by Django 4.0.6 on 2022-08-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0015_alter_news_photo_1_alter_news_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_5',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='news/', verbose_name='Картинка новини'),
        ),
    ]
