# Generated by Django 4.0.6 on 2022-08-04 10:45

from django.db import migrations, models
import nio_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0016_alter_news_photo_2_alter_news_photo_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo_1',
            field=models.ImageField(max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_5',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=nio_app.models.News.directory_path, verbose_name='Картинка новини'),
        ),
    ]
