# Generated by Django 4.0.6 on 2022-08-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0017_alter_news_photo_1_alter_news_photo_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsPubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=5000, verbose_name='Повідомлення')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.reviewspubs', verbose_name='До кого')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nio_app.publications', verbose_name='Публікація')),
            ],
            options={
                'verbose_name': 'Відгук на публікацію',
                'verbose_name_plural': 'Відгуки на публікацію',
            },
        ),
        migrations.CreateModel(
            name='ReviewsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=5000, verbose_name='Повідомлення')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nio_app.publications', verbose_name='Новина')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nio_app.reviewsnews', verbose_name='До кого')),
            ],
            options={
                'verbose_name': 'Відгук на новину',
                'verbose_name_plural': 'Відгуки на новину',
            },
        ),
    ]
