# Generated by Django 4.0.6 on 2022-08-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0018_reviewspubs_reviewsnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsnews',
            name='pub_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата коментарія'),
        ),
        migrations.AddField(
            model_name='reviewspubs',
            name='pub_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата коментарія'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='Дата новини'),
        ),
    ]
