# Generated by Django 4.0.6 on 2022-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nio_app', '0019_reviewsnews_pub_date_reviewspubs_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsnews',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата коментарія'),
        ),
        migrations.AlterField(
            model_name='reviewspubs',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата коментарія'),
        ),
    ]
