# Generated by Django 4.0.6 on 2022-09-02 13:46

import divisions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва підрозділу')),
                ('abr', models.CharField(help_text='не більше ніж 10 символів', max_length=10, verbose_name='Абрівіатура підрозділу')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('main_div', models.CharField(help_text='не більше ніж 10 символів', max_length=10, null=True, verbose_name='Абрівіатура підрозділу')),
                ('description', models.TextField(help_text='Введіть короткий опис підрозділу', max_length=5000, verbose_name='Опис підрозділу')),
                ('coops', models.ManyToManyField(to='nio_app.cooperation', verbose_name='Підрозділи взаємодії')),
                ('locs', models.ManyToManyField(to='nio_app.location', verbose_name='Розміщення')),
            ],
            options={
                'verbose_name': 'Підрозділи',
                'verbose_name_plural': 'Підрозділи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DivisionsPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=divisions.models.DivisionsPics.directory_path, verbose_name='Фото підрозділу')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisions.divisions', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Картинка до підрозділу',
                'verbose_name_plural': 'Картинки до підрозділів',
                'ordering': ['div'],
            },
        ),
        migrations.AddField(
            model_name='divisions',
            name='pics',
            field=models.ManyToManyField(blank=True, null=True, to='divisions.divisionspics', verbose_name='Картинка до підрозділу'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='theses',
            field=models.ManyToManyField(to='nio_app.theses', verbose_name='Тези'),
        ),
    ]
