# Generated by Django 4.0.6 on 2022-09-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisionspics',
            options={'verbose_name': 'Картинка до підрозділу', 'verbose_name_plural': 'Картинки до підрозділів'},
        ),
        migrations.RemoveField(
            model_name='divisionspics',
            name='div',
        ),
        migrations.AlterField(
            model_name='divisions',
            name='pics',
            field=models.ManyToManyField(to='divisions.divisionspics', verbose_name='Картинка до підрозділу'),
        ),
    ]
