# Generated by Django 4.0.6 on 2022-09-05 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=5000, verbose_name='Повідомлення')),
                ('pub_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата коментарія')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.reviewsprojects', verbose_name='До кого')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Відгук на проект',
                'verbose_name_plural': 'Відгуки на проект',
                'ordering': ['-pub_date'],
            },
        ),
    ]
