# Generated by Django 4.0.6 on 2022-09-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_reviewsprojects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='pics',
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(help_text='Введіть короткий опис мети проекту', max_length=5000, verbose_name='Опис проекту'),
        ),
    ]
