# Generated by Django 4.0.6 on 2022-09-09 07:13

from django.db import migrations, models
import projects.models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projects_docs_remove_projects_pics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsdocs',
            name='doc',
            field=models.FileField(blank=True, help_text='Усі файли проекту повинні бути додані до архіву у форматі *.zip чи *.rar і завантажені єдиним файлом', max_length=500, null=True, upload_to=projects.models.ProjectsDocs.directory_path, validators=[projects.validators.validate_file_extension]),
        ),
    ]
