# Generated by Django 4.0.6 on 2022-09-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='ПІБ')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('tabel', models.CharField(help_text='не більше ніж 5 символів', max_length=5, unique=True, verbose_name='Табельный номер')),
                ('prof', models.CharField(help_text='не більше ніж 100 символів', max_length=100, verbose_name='Посада')),
                ('oklad', models.IntegerField(verbose_name='Оклад')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата народження')),
                ('phone', models.CharField(help_text='формат +38(ХХХ)-ХХХ-ХХ-ХХ', max_length=18, verbose_name='Номер телефону')),
                ('adress', models.CharField(help_text='формат пр/вул/провулок ХХХХХ д.ХХ кв.ХХ', max_length=100, verbose_name='Домашня адреса')),
                ('photo', models.ImageField(upload_to='workers_foto/', verbose_name='Фото')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisions.divisions', verbose_name='Підрозділ')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
                'ordering': ['fio'],
            },
        ),
    ]
