# Generated by Django 4.0.6 on 2022-09-02 13:47

from django.db import migrations, models
import django.db.models.deletion
import publics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('divisions', '0001_initial'),
        ('nio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше ніж 200 символів', max_length=200, verbose_name='Назва публікації')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(help_text='Введіть короткий опис мети публікації', max_length=5000, null=True, verbose_name='Короткий опис')),
                ('text', models.TextField(help_text='не більше 50 000 символів', max_length=50000, null=True, verbose_name='Текст публікації')),
                ('pub_date', models.DateField(null=True, verbose_name='Дата піблікації')),
                ('photo_1', models.ImageField(max_length=500, null=True, upload_to=publics.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('photo_2', models.ImageField(blank=True, max_length=500, null=True, upload_to=publics.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('photo_3', models.ImageField(blank=True, max_length=500, null=True, upload_to=publics.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('photo_4', models.ImageField(blank=True, max_length=500, null=True, upload_to=publics.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('photo_5', models.ImageField(blank=True, max_length=500, null=True, upload_to=publics.models.Publications.directory_path, verbose_name='Картинка публікації')),
                ('doc', models.FileField(blank=True, max_length=500, null=True, upload_to=publics.models.Publications.directory_path, verbose_name='Файл публікації')),
                ('author', models.ManyToManyField(help_text='Оберіть автора/авторів публікації', to='staff.staff', verbose_name='Автор')),
                ('category', models.ManyToManyField(help_text='оберіть категорію/категорії', to='nio_app.categories', verbose_name='Оберіть категорію')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisions.divisions', verbose_name='Назва підрозділу')),
            ],
            options={
                'verbose_name': 'Публікація',
                'verbose_name_plural': 'Публікації',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewsPubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=5000, verbose_name='Повідомлення')),
                ('pub_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата коментарія')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publics.reviewspubs', verbose_name='До кого')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publics.publications', verbose_name='Публікація')),
            ],
            options={
                'verbose_name': 'Відгук на публікацію',
                'verbose_name_plural': 'Відгуки на публікацію',
                'ordering': ['-pub_date'],
            },
        ),
    ]
